---
language: php

cache:
  directories:
  - $HOME/.composer/cache/files

php:
- nightly
- 7.2
- 7.1
- 7.0

env:
  global:
  - COMPOSER=composer-dev.json
  # - PATH=$TRAVIS_BUILD_DIR/bin::$PATH

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_install:
- go get -u github.com/jingweno/ccat
# Disabling Xdebug - Debugger and Profiler Tool for PHP
- |
  php -r "print_r(get_loaded_extensions(TRUE));"
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    install --directory ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/on-demand
    php -r "print_r(get_loaded_extensions(TRUE));"
  fi

install:
- |
  composer require symfony/flex
  composer require symfony/yaml
  composer require symfony/dotenv --dev
  composer require symfony/orm-pack
  composer require friendsofsymfony/ckeditor-bundle
  composer require easycorp/easyadmin-bundle
  composer require symfony/profiler-pack --dev
  composer require symfony/web-server-bundle --dev
  composer initialize # -- --ansi

script:
- composer require --no-scripts sensiolabs/security-checker &> /dev/null && composer security:check composer-dev.lock -- --end-point=http://security.sensiolabs.org/check_lock --ansi

script:
- $GOPATH/bin/ccat composer.json
after_script:
- ls --almost-all --color
